name: TesseractTag
main: club.tesseract.tesseracttag.TesseractTag
version: @version@
authors: ["ThousandthStar", "TropicalShadow"]
api-version: 1.18
commands:
  setHunter:
    description: "Set hunter"